ALTER TABLE photo_books ADD COLUMN IF NOT EXISTS body_font VARCHAR(50) NOT NULL DEFAULT 'pt-serif';
ALTER TABLE photo_books ADD COLUMN IF NOT EXISTS heading_font VARCHAR(50) NOT NULL DEFAULT 'source-sans-3';
ALTER TABLE photo_books ADD COLUMN IF NOT EXISTS body_font_size REAL NOT NULL DEFAULT 11.0;
ALTER TABLE photo_books ADD COLUMN IF NOT EXISTS body_line_height REAL NOT NULL DEFAULT 15.0;
ALTER TABLE photo_books ADD COLUMN IF NOT EXISTS h1_font_size REAL NOT NULL DEFAULT 18.0;
ALTER TABLE photo_books ADD COLUMN IF NOT EXISTS h2_font_size REAL NOT NULL DEFAULT 13.0;
ALTER TABLE photo_books ADD COLUMN IF NOT EXISTS caption_opacity REAL NOT NULL DEFAULT 0.85;
ALTER TABLE photo_books ADD COLUMN IF NOT EXISTS caption_font_size REAL NOT NULL DEFAULT 9.0;
