-- Native photo management schema.
--
-- Introduces the tables photo-sorter needs to manage photos, users,
-- albums, labels, faces, markers, and subjects on its own — so that
-- PhotoPrism can be retired in a later milestone. UIDs are VARCHAR(32)
-- strings generated by the application (PhotoPrism-style: prefix +
-- random suffix), not by the database. Existing tables (embeddings,
-- faces, era_embeddings, sessions, photo_books, text_versions,
-- text_check_results, etc.) are left untouched.

-- users: native auth, replaces PhotoPrism's user store.
CREATE TABLE IF NOT EXISTS users (
    uid VARCHAR(32) PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    display_name VARCHAR(255) NOT NULL DEFAULT '',
    email VARCHAR(255) NOT NULL DEFAULT '',
    password_hash TEXT NOT NULL,
    role VARCHAR(16) NOT NULL CHECK (role IN ('admin', 'editor', 'viewer')),
    disabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_login_at TIMESTAMPTZ
);

-- photos: primary photo metadata table, replaces PhotoPrism's photos.
CREATE TABLE IF NOT EXISTS photos (
    uid VARCHAR(32) PRIMARY KEY,
    file_hash VARCHAR(64) NOT NULL UNIQUE,
    file_path TEXT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_size BIGINT NOT NULL,
    file_mime VARCHAR(64) NOT NULL,
    file_width INT NOT NULL DEFAULT 0,
    file_height INT NOT NULL DEFAULT 0,
    file_orientation INT NOT NULL DEFAULT 1,
    taken_at TIMESTAMPTZ,
    taken_at_source VARCHAR(16) NOT NULL DEFAULT 'unknown'
        CHECK (taken_at_source IN ('exif', 'filename', 'manual', 'ai', 'unknown')),
    title VARCHAR(255) NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '',
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    altitude DOUBLE PRECISION,
    camera_make VARCHAR(64) NOT NULL DEFAULT '',
    camera_model VARCHAR(128) NOT NULL DEFAULT '',
    lens_model VARCHAR(128) NOT NULL DEFAULT '',
    iso INT,
    aperture DOUBLE PRECISION,
    exposure VARCHAR(32) NOT NULL DEFAULT '',
    focal_length DOUBLE PRECISION,
    exif JSONB NOT NULL DEFAULT '{}'::jsonb,
    favorite BOOLEAN NOT NULL DEFAULT FALSE,
    private BOOLEAN NOT NULL DEFAULT FALSE,
    archived_at TIMESTAMPTZ,
    uploaded_by VARCHAR(32) REFERENCES users(uid) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_photos_taken_at ON photos(taken_at DESC);
CREATE INDEX IF NOT EXISTS idx_photos_archived_at ON photos(archived_at)
    WHERE archived_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_photos_exif ON photos USING GIN (exif);
CREATE INDEX IF NOT EXISTS idx_photos_lat_lng ON photos(lat, lng);

-- photo_files: physical files belonging to a photo (stacks — RAW+JPEG,
-- HEIC+JPEG sidecars, edits). Exactly one file per photo is the
-- primary, enforced by a partial unique index.
CREATE TABLE IF NOT EXISTS photo_files (
    id BIGSERIAL PRIMARY KEY,
    photo_uid VARCHAR(32) NOT NULL REFERENCES photos(uid) ON DELETE CASCADE,
    file_path TEXT NOT NULL,
    file_hash VARCHAR(64) NOT NULL,
    file_size BIGINT NOT NULL,
    file_mime VARCHAR(64) NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    role VARCHAR(16) NOT NULL DEFAULT 'original'
        CHECK (role IN ('original', 'sidecar', 'edited')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (photo_uid, file_path)
);
CREATE INDEX IF NOT EXISTS idx_photo_files_photo_uid ON photo_files(photo_uid);
CREATE UNIQUE INDEX IF NOT EXISTS idx_photo_files_one_primary
    ON photo_files(photo_uid)
    WHERE is_primary = TRUE;

-- albums: user-curated and auto-generated groupings of photos.
CREATE TABLE IF NOT EXISTS albums (
    uid VARCHAR(32) PRIMARY KEY,
    slug VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    type VARCHAR(16) NOT NULL DEFAULT 'album'
        CHECK (type IN ('album', 'folder', 'moment', 'state', 'month')),
    cover_photo_uid VARCHAR(32) REFERENCES photos(uid) ON DELETE SET NULL,
    favorite BOOLEAN NOT NULL DEFAULT FALSE,
    private BOOLEAN NOT NULL DEFAULT FALSE,
    order_by VARCHAR(16) NOT NULL DEFAULT 'newest',
    created_by VARCHAR(32) REFERENCES users(uid) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- album_photos: m:n photo ↔ album relation with explicit ordering.
CREATE TABLE IF NOT EXISTS album_photos (
    album_uid VARCHAR(32) NOT NULL REFERENCES albums(uid) ON DELETE CASCADE,
    photo_uid VARCHAR(32) NOT NULL REFERENCES photos(uid) ON DELETE CASCADE,
    sort_order INT NOT NULL DEFAULT 0,
    added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (album_uid, photo_uid)
);
CREATE INDEX IF NOT EXISTS idx_album_photos_photo_uid ON album_photos(photo_uid);

-- labels: tags/categories applied to photos.
CREATE TABLE IF NOT EXISTS labels (
    uid VARCHAR(32) PRIMARY KEY,
    slug VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    priority INT NOT NULL DEFAULT 0,
    favorite BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- photo_labels: m:n photo ↔ label relation with provenance.
CREATE TABLE IF NOT EXISTS photo_labels (
    photo_uid VARCHAR(32) NOT NULL REFERENCES photos(uid) ON DELETE CASCADE,
    label_uid VARCHAR(32) NOT NULL REFERENCES labels(uid) ON DELETE CASCADE,
    source VARCHAR(16) NOT NULL DEFAULT 'manual'
        CHECK (source IN ('manual', 'ai', 'import')),
    uncertainty INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (photo_uid, label_uid)
);
CREATE INDEX IF NOT EXISTS idx_photo_labels_label_uid ON photo_labels(label_uid);

-- subjects: people / pets / other recurring subjects of face markers.
CREATE TABLE IF NOT EXISTS subjects (
    uid VARCHAR(32) PRIMARY KEY,
    slug VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(16) NOT NULL DEFAULT 'person'
        CHECK (type IN ('person', 'pet', 'other')),
    favorite BOOLEAN NOT NULL DEFAULT FALSE,
    private BOOLEAN NOT NULL DEFAULT FALSE,
    notes TEXT NOT NULL DEFAULT '',
    cover_photo_uid VARCHAR(32) REFERENCES photos(uid) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- markers: face/label bounding boxes on photos. Coordinates are
-- relative (0..1) in display space. Replaces PhotoPrism markers.
CREATE TABLE IF NOT EXISTS markers (
    uid VARCHAR(32) PRIMARY KEY,
    photo_uid VARCHAR(32) NOT NULL REFERENCES photos(uid) ON DELETE CASCADE,
    subject_uid VARCHAR(32) REFERENCES subjects(uid) ON DELETE SET NULL,
    type VARCHAR(16) NOT NULL DEFAULT 'face'
        CHECK (type IN ('face', 'label')),
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    w DOUBLE PRECISION NOT NULL,
    h DOUBLE PRECISION NOT NULL,
    score INT NOT NULL DEFAULT 0,
    invalid BOOLEAN NOT NULL DEFAULT FALSE,
    reviewed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_markers_photo_uid ON markers(photo_uid);
CREATE INDEX IF NOT EXISTS idx_markers_subject_uid ON markers(subject_uid);
